$(".li2").mouseover(function(){
     $(".erweima").fadeIn();    
})
$(".li2").mouseout(function(){
    $(".erweima").fadeOut();    
})
$(".li3").mouseover(function(){
    $(".gouwuc").fadeIn();
})
$(".li3").mouseout(function(){
    $(".gouwuc").fadeOut();    
})
$(".look").mouseover(function(){
    $(".sousuo").fadeIn();
})
$(".look").mouseout(function(){
    $(".sousuo").fadeOut();    
})
